import type { Metadata } from "next";

export const metadata: Metadata = {
  title: { default: "Admin", template: "%s · KSF Admin" },
  // Belt and braces alongside robots.ts — the admin area must never appear
  // in search results.
  robots: { index: false, follow: false, nocache: true },
};

// LayoutProps is a global helper generated by `next dev` / `next build`.
// Hand-writing `{ children: React.ReactNode }` fails the generated route
// validator in Next 16 — see docs/01-app/01-getting-started/03-layouts-and-pages.
export default function AdminLayout(props: LayoutProps<"/admin">) {
  return <div className="min-h-screen bg-surface-2">{props.children}</div>;
}
